updating workflows

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -140,6 +140,12 @@ jobs:
         port: ${{ secrets.EC2_SSH_PORT }}
         script: |
           set -e
+          if sudo docker ps -a --filter name=stock-app | grep -q stock-app; then
+            if ! sudo docker stop stock-app; then
+              echo "Failed to stop stock-app container"
+              exit 1
+            fi
+          fi
           if sudo docker container ls -a --filter name=current_springboot_1 | grep -q current_springboot_1; then
             if ! sudo docker container rm current_springboot_1; then
               echo "Failed to remove current_springboot_1 container"
@@ -156,9 +162,7 @@ jobs:
             echo "Failed to prune Docker images"
             exit 1
           fi
-
-      #          sudo docker-compose down
-#          sudo docker stop stock-app
+    
 
     - name: Update Elastic Beanstalk environment
       run: |
